### ISSUE TITLE
Report the state of agents back to clients (e.g., reached destination)

### ISSUE THREAD

**Issue by andriyDev** [andriyDev/landmass#22]
Clients need to be able to know when they've reached the destination! Or what other state agents are in.

**Comment by tviel** [comment]
I've seen, that there is already a corresponding function to check, if the Agent reached its target (`pub(crate) fn has_reached_target` in _Agent.rs_) and checked in `update` of _lib.rs_. For me, it looks like it could be enough to add an enum with the agents state and set accordingly in the update loop of landmass to expose it over the Agent struct.

**Comment by andriyDev** [comment]
Yeah I like this! We should have a few variants of this state. I'm picturing `Idle`, `ReachedTarget`, `Moving`, `NoPath` (maybe that's part of #8 though?). In the future, we'll probably want `LookingForPath` as well to handle async pathfinding or something, but we don't have to worry about that for now.

**Comment by andriyDev** [comment]
Actually if we stick `PathStats` in the `Moving` and `NoPath` variants, that might also be enough to also solve #8. Although maybe users would want to recieve an event every time a path failed? Or we can just have every pathfind generate a unique ID, and users have to keep track of when that changes 🤔
