### ISSUE TITLE
[Question] Support for incremental heuristic search?

### ISSUE THREAD

**Issue by teohhanhui** [andriyDev/landmass#92]
e.g. https://stackoverflow.com/a/8294631/1529493

https://idm-lab.org/project-a.html

**Comment by andriyDev** [comment]
Hi, sorry for the delay. I don't think I'm interested in supporting this. Generally I think this makes agents look less intelligent than they are (which is already enough of a problem haha).

What is your use case?

**Comment by teohhanhui** [comment]
> What is your use case?

Turn-based strategy game like Civilization VI

My probably wrong / incomplete observations:
https://github.com/teohhanhui/hexciv/blob/dc60fce7601d4a872057d10eadd1107b056b62c6/crates/hexciv/src/unit.rs#L1009-L1018
